Repository TripTripNow/TodayTrip, pull requests merged in 2024-02, with the labels that each got.

#66 [#48] 유저 기능 개발
  package-lock.json
  package.json
  src/api/axiosInstance.ts
  src/api/user/user.ts
  src/components/Input/Input.module.css
  src/components/User/SocialLogin.tsx
  src/components/common/Navbar/ProfileDropDown.module.css
  src/components/common/Navbar/ProfileDropDown.tsx
  src/middleware.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/next-auth.d.ts
  src/types/user.ts
  src/utils/passwordCheck.ts
Labels: 🐷 Feat

#60 [#56] 예약 상세 페이지 구현
  public/icons/icon-arrowBack.svg
  public/icons/icon-arrowRight.svg
  src/components/Reservations/Card/Card.tsx
  src/constants/reservation.ts
  src/pages/mypage/reservations/[id]/ReservationId.module.css
  src/pages/mypage/reservations/[id]/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/types/reservations.ts
Labels: 🐷 Feat, 🐳 Style

#62 [#47] 예약 현황 페이지 작성
  public/icons/icon-calendararrow.svg
  src/components/FilterDropdown/FilterDropdown.tsx
  src/components/Home/AllExperience/AllExperience.tsx
  src/components/Home/Card/Card.tsx
  src/components/Home/CardDetail/CardDetail.tsx
  src/components/Home/PopularExperience/PopularExperience.tsx
  src/components/Modal/ModalLayout/ModalLayout.tsx
  src/components/MyPage/ProfileMenuBox.tsx
  src/components/ReservationDashboard/Calendar/Calendar.module.css
  src/components/ReservationDashboard/Calendar/Calendar.tsx
  src/components/ReservationDashboard/Calendar/CalendarHeader.module.css
  src/components/ReservationDashboard/Calendar/CalendarHeader.tsx
  src/components/ReservationDashboard/Chips/Chips.module.css
  src/components/ReservationDashboard/Chips/Chips.tsx
  src/components/ReservationDashboard/Modal/Modal.module.css
  src/components/ReservationDashboard/Modal/Modal.tsx
  src/components/ReservationDashboard/Modal/ModalContent.module.css
  src/components/ReservationDashboard/Modal/ModalContent.tsx
  src/components/ReservationDashboard/Modal/ModalDetailedCard.module.css
  src/components/ReservationDashboard/Modal/ModalDetailedCard.tsx
  src/components/ReservationDashboard/mock.ts
  src/components/common/Button/Button.module.css
  src/components/common/DropDown/Dropdown.module.css
  src/components/common/DropDown/Dropdown.tsx
  src/components/common/NoResult/NoResult.module.css
  src/components/common/NoResult/NoResult.tsx
  src/constants/calendar.ts
  src/constants/dropdown.ts
  src/constants/mock.ts
  src/hooks/ReservationDashboard/useCalendar.ts
  src/hooks/common/useBodyScrollLock.ts
  src/hooks/common/useInfiniteScroll.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/activities/reservation-dashboard/ReservationDashboard.module.css
  src/pages/mypage/activities/reservation-dashboard/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/styles/variables.css
  src/types/api.ts
  src/types/myActivities/index.ts
  src/utils/ReservationDashboard/calculateDaysInMonth.ts
  src/utils/ReservationDashboard/formatDateStringByDot.ts
  src/utils/ReservationDashboard/showTodayDate.ts
Labels: 🐷 Feat, 🐹 Fix, 🐸 Refactor

#72 [#69] mypage - 내 정보페이지 내 정보 조회 api
  src/api/axiosInstance.ts
  src/api/user/user.ts
  src/constants/queryKeys.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/mypage/index.tsx
  src/types/users/index.ts
Labels: 🐹 Fix

#64 [#45] 내 체험 등록/수정 페이지 퍼블리싱
  next.config.js
  package-lock.json
  package.json
  public/icons/icon-imgClose.svg
  public/icons/icon-logoMark.png
  public/icons/icon-logoMarker.svg
  public/icons/icon-minusButton.svg
  public/icons/icon-plus.svg
  public/icons/icon-plusButton.svg
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Activities/ActivitiesForm.tsx
  src/components/MyPage/Activities/Add/ImageContainer.tsx
  src/components/MyPage/Activities/Add/MapContainer.module.css
  src/components/MyPage/Activities/Add/MapContainer.tsx
  src/components/MyPage/Activities/Add/ReservationTime.tsx
  src/components/MyPage/ProfileInput.tsx
  src/components/common/DatePicker/DatePicker.module.css
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/DropDown/Dropdown.module.css
  src/components/common/DropDown/Dropdown.tsx
  src/pages/_app.tsx
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/add/Add.module.css
  src/pages/mypage/activities/add/index.tsx
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/reservations/[id]/ReservationId.module.css
Labels: 🐷 Feat

#63 [#53] 체험 상세 페이지 퍼블리싱
  .gitignore
  next.config.js
  package-lock.json
  package.json
  public/icons/icon-littleEmptyStar.svg
  public/icons/icon-location.svg
  public/icons/icon-minus.svg
  public/images/a.png
  public/images/block.png
  public/images/flower.png
  public/images/flower2.png
  public/images/img-mapMarker.png
  public/images/nextjs.png
  public/images/react.png
  src/components/Activities/Header/Header.module.css
  src/components/Activities/Header/Header.tsx
  src/components/Activities/MainContent/MainContent.module.css
  src/components/Activities/MainContent/MainContent.tsx
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.module.css
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.tsx
  src/components/Activities/ReviewList/ReviewList.module.css
  src/components/Activities/ReviewList/ReviewList.tsx
  src/components/Activities/mock.ts
  src/components/Home/AllExperience/AllExperience.tsx
  src/components/Home/Card/Card.tsx
  src/components/Home/CardDetail/CardDetail.tsx
  src/components/Modal/AlertModal/AlertModal.module.css
  src/components/Modal/ReservationModal/ReservationModal.module.css
  src/components/Modal/ReservationModal/ReservationModal.tsx
  src/components/Modal/ReviewModal/ReviewModal.tsx
  src/components/Modal/ReviewModal/Star/Star.tsx
  src/components/MyPage/Reservations/Card/Card.module.css
  src/components/MyPage/Reservations/Card/Card.tsx
  src/components/MyPage/Reservations/mock.ts
  src/components/ReservationDashboard/Calendar/Calendar.tsx
  src/components/ReservationDashboard/mock.ts
  src/components/Reservations/Card/Card.tsx
  src/components/common/Button/Button.module.css
  src/components/common/DropDown/Dropdown.tsx
  src/components/common/Pagination/Pagination.module.css
  src/components/common/Pagination/Pagination.tsx
  src/constants/ratingArray.ts
  src/pages/activities/[id]/Activity.module.css
  src/pages/activities/[id]/index.tsx
  src/pages/api/geocode.ts
  src/pages/index.tsx
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/reservations/Reservations.module.css
  src/pages/mypage/reservations/[id]/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  src/types/Activities/index.ts
  src/types/Calendar.ts
  src/types/common/api.ts
  src/types/myActivities/index.ts
  src/types/reservations.ts
  src/utils/determineSatisfaction.ts
  src/utils/formatDateString.ts
Labels: 🐷 Feat, 🐳 Style

#83 [#75] 체험 상세 페이지 API 연동
  package-lock.json
  public/icons/icon-smallPlus.svg
  src/api/activities/index.ts
  src/api/myActivities/index.ts
  src/components/Activities/Header/Header.module.css
  src/components/Activities/Header/Header.tsx
  src/components/Activities/MainContent/MainContent.module.css
  src/components/Activities/MainContent/MainContent.tsx
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.tsx
  src/components/Activities/ReviewList/ReviewList.module.css
  src/components/Activities/ReviewList/ReviewList.tsx
  src/components/Activities/mock.ts
  src/components/Modal/AlertModal/AlertModal.module.css
  src/components/Modal/AlertModal/AlertModal.tsx
  src/components/Modal/ReservationModal/ReservationModal.tsx
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Reservations/Card/Card.tsx
  src/components/Reservations/Card/Card.tsx
  src/components/common/Map/Map.module.css
  src/components/common/Map/Map.tsx
  src/constants/queryKeys.ts
  src/pages/activities/[id]/index.tsx
  src/pages/mypage/reservations/[id]/index.tsx
  src/types/Activities/index.ts
  src/types/common/api.ts
  src/utils/determineSatisfaction.ts
  tsconfig.json
Labels: 🐷 Feat

#92 [#88] 예약 내역 페이지 API 연동
  src/api/myReservations/index.ts
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.tsx
  src/components/Modal/ReviewModal/ReviewModal.module.css
  src/components/Modal/ReviewModal/ReviewModal.tsx
  src/components/Modal/ReviewModal/Star/Star.tsx
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Reservations/Card/Card.tsx
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.module.css
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.tsx
  src/components/MyPage/Reservations/mock.ts
  src/constants/queryKeys.ts
  src/constants/reservation.ts
  src/pages/mypage/reservations/[id]/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/types/common/api.ts
  src/types/myReservations/index.ts
Labels: 🐷 Feat

#74 [#70] 메인페이지 API 연동
  .husky/pre-commit
  public/icons/icon-reset.svg
  public/icons/icon-right-arrow.svg
  public/images/img-mainBanner1.png
  public/images/img-mainBanner2.png
  public/images/img-mainBanner3.png
  public/images/img-noImage.png
  src/api/activities/index.ts
  src/api/user/index.ts
  src/components/Footer/Footer.tsx
  src/components/Home/AllExperience/AllExperience.module.css
  src/components/Home/AllExperience/AllExperience.tsx
  src/components/Home/Banner/Banner.module.css
  src/components/Home/Banner/Banner.tsx
  src/components/Home/Card/Card.module.css
  src/components/Home/CardDetail/CardDetail.module.css
  src/components/Home/CardDetail/CardDetail.tsx
  src/components/Home/LinkButton/LinkButton.module.css
  src/components/Home/LinkButton/LinkButton.tsx
  src/components/Home/PopularExperience/PopularExperience.module.css
  src/components/Home/PopularExperience/PopularExperience.tsx
  src/components/Home/Searchbar/Searchbar.module.css
  src/components/Home/Searchbar/Searchbar.tsx
  src/components/MyPage/ProfileInput.tsx
  src/components/ReservationDashboard/mock.ts
  src/constants/dropdown.ts
  src/constants/queryKeys.ts
  src/hooks/Home/useBanner.ts
  src/hooks/Home/useHome.ts
  src/hooks/Home/usePopularExperience.ts
  src/hooks/common/useDeviceType.ts
  src/pages/Home.module.css
  src/pages/api/auth/[...nextauth].ts
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/types/activities/index.ts
  src/types/common/api.ts
Labels: 🐷 Feat, 🐹 Fix

#91 [#86] 내 체험 관리 페이지 API 연동
  src/api/myActivities/index.ts
  src/components/Activities/Header/Header.tsx
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Activities/ActivitiesMock.ts
  src/constants/queryKeys.ts
  src/pages/mypage/activities/index.tsx
Labels: 🐷 Feat

#85 [#71] 예약 상세 페이지 API 연동
  src/api/myReservations/index.ts
  src/components/Modal/ReviewModal/ReviewModal.tsx
  src/components/MyPage/Reservations/Details/CheckStatus.module.css
  src/components/MyPage/Reservations/Details/CheckStatus.tsx
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.tsx
  src/pages/mypage/reservations/[id]/ReservationId.module.css
  src/pages/mypage/reservations/[id]/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/types/common/api.ts
Labels: 🐷 Feat

#96 [#84] nav바 API 연동
  src/api/axiosInstance.ts
  src/api/myNotifications/index.ts
  src/components/MyPage/ProfileInput.tsx
  src/components/MyPage/ProfileMenuBox.module.css
  src/components/MyPage/ProfileMenuBox.tsx
  src/components/MyPage/profileInput.module.css
  src/components/common/Navbar/AlarmModal.module.css
  src/components/common/Navbar/AlarmModal.tsx
  src/components/common/Navbar/Navbar.module.css
  src/components/common/Navbar/Navbar.tsx
  src/constants/queryKeys.ts
  src/hooks/common/useInfiniteScroll.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/mypage/index.tsx
  src/types/myNotifications/index.ts
  src/utils/chageDateForm.ts
Labels: 🐷 Feat

#93 [#73] 예약 현황 페이지 API 연동
  src/api/myActivities/index.ts
  src/components/Activities/Header/Header.tsx
  src/components/Modal/ReviewModal/ReviewModal.tsx
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/ReservationDashboard/Calendar/Calendar.module.css
  src/components/ReservationDashboard/Calendar/Calendar.tsx
  src/components/ReservationDashboard/Modal/Modal.module.css
  src/components/ReservationDashboard/Modal/Modal.tsx
  src/components/ReservationDashboard/Modal/ModalContent.module.css
  src/components/ReservationDashboard/Modal/ModalContent.tsx
  src/components/ReservationDashboard/Modal/ModalDetailedCard.module.css
  src/components/ReservationDashboard/Modal/ModalDetailedCard.tsx
  src/components/ReservationDashboard/mock.ts
  src/components/common/Button/Button.module.css
  src/components/common/DropDown/Dropdown.module.css
  src/components/common/DropDown/Dropdown.tsx
  src/components/common/NoResult/NoResult.module.css
  src/components/common/Toast/Toast.tsx
  src/constants/queryKeys.ts
  src/hooks/Home/useHome.ts
  src/hooks/Home/usePopularExperience.ts
  src/hooks/ReservationDashboard/useCalendar.ts
  src/hooks/ReservationDashboard/useModalContent.ts
  src/hooks/ReservationDashboard/useModalDetailedCard.ts
  src/hooks/ReservationDashboard/useReservationDashboard.ts
  src/hooks/common/useInfiniteScroll.ts
  src/pages/Home.module.css
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/activities/reservation-dashboard/index.tsx
  src/types/activities/index.ts
  src/types/common/api.ts
  src/types/myActivities/index.ts
  src/utils/ReservationDashboard/formatDateStringByDot.ts
  src/utils/ReservationDashboard/showTodayDate.ts
Labels: 🐷 Feat, 🐸 Refactor

#109 [#108] isError useEffect 쓰지 않아 발생하는 오류 해결
  src/components/ReservationDashboard/Modal/Modal.tsx
  src/hooks/Home/useHome.ts
  src/hooks/Home/usePopularExperience.ts
  src/hooks/ReservationDashboard/useCalendar.ts
  src/hooks/ReservationDashboard/useModalContent.ts
  src/hooks/ReservationDashboard/useReservationDashboard.ts
Labels: 🐹 Fix

#104 [#97] 이미지 오류 대체 컴포넌트 작성
  src/components/Home/AllExperience/AllExperience.tsx
  src/components/Home/Card/Card.tsx
  src/components/Home/CardDetail/CardDetail.tsx
  src/components/common/ImageFallback/ImageFallback.tsx
Labels: 🐷 Feat, 🐸 Refactor

#110 [#103] 리액트 데이트 피커 리팩토링
  src/components/common/DatePicker/DatePicker.module.css
  src/components/common/DatePicker/DatePicker.tsx
Labels: 🐳 Style, 🐸 Refactor

#106 [#101] nav바, 마이페이지 수정
  .husky/pre-commit
  public/icons/icon-activity-add.svg
  src/components/MyPage/ProfileInput.tsx
  src/components/MyPage/ProfileMenuBox.tsx
  src/components/MyPage/profileInput.module.css
  src/components/common/Navbar/AlarmModal.tsx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/ProfileDropDown.tsx
Labels: 🐸 Refactor

#111 [#107] 회원가입, 로그인 페이지 에러 메세지 오류
  src/components/Input/Input.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/utils/passwordCheck.ts
Labels: 🐸 Refactor

#100 [#76] 내 체험 등록/수정 페이지 API 연동
  src/api/activities/index.ts
  src/api/myActivities/index.ts
  src/components/Modal/AlertModal/AlertModal.tsx
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Activities/ActivitiesForm.tsx
  src/components/MyPage/Activities/Add/ImageContainer.tsx
  src/components/MyPage/Activities/Add/MapContainer.tsx
  src/components/MyPage/Activities/Add/ReservationTime.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/DropDown/Dropdown.module.css
  src/components/common/DropDown/Dropdown.tsx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/ProfileDropDown.module.css
  src/constants/queryKeys.ts
  src/pages/mypage/activities/Activities.module.css
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/add/Add.module.css
  src/pages/mypage/activities/add/index.tsx
  src/pages/mypage/activities/index.tsx
  src/types/activities/index.ts
  src/types/common/api.ts
  src/types/myActivities/index.ts
Labels: 🐷 Feat

#116 [#114] nav, footer 성능 개선
  next.config.js
  src/components/Footer/Footer.module.css
  src/components/MyPage/ProfileInput.tsx
  src/components/common/Navbar/Navbar.module.css
  src/components/common/Navbar/Navbar.tsx
Labels: 🐸 Refactor

#122 [#113] 예약 상세 페이지 리팩토링
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.module.css
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.tsx
  src/pages/mypage/activities/Activities.module.css
  src/pages/mypage/reservations/[id]/ReservationId.module.css
Labels: 🐳 Style, 🐸 Refactor

#123 [#120] 마이페이지, nav바 refactor
  src/components/MyPage/profileInput.module.css
  src/components/common/Navbar/AlarmModal.tsx
  src/components/common/Navbar/Navbar.module.css
  src/components/common/Navbar/Navbar.tsx
  src/pages/api/auth/[...nextauth].ts
Labels: 🐸 Refactor

#126 [#124] 메타 태그 설정
  public/images/TodayTripLogo2.png
  src/components/HeadMeta/HeadMeta.tsx
  src/constants/metaTag.ts
  src/pages/activities/[id]/index.tsx
  src/pages/index.tsx
  src/pages/mypage/activities/add/index.tsx
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/activities/reservation-dashboard/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/reservations/[id]/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🐷 Feat

#127 [#118] 내 체험 관리, 체험 등록, 수정 페이지 리팩토링
  src/components/Input/Input.tsx
  src/components/MyPage/Activities/ActivitiesForm.tsx
  src/constants/metaTag.ts
  src/constants/user.ts
  src/hooks/Mypage/Activities/Add/useMyActivitiesAdd.tsx
  src/hooks/Mypage/Activities/Edit/useMyActivitiesEdit.tsx
  src/hooks/Mypage/Activities/useMyActivities.tsx
  src/hooks/Mypage/Activities/useMyActivitiesForm.tsx
  src/pages/mypage/activities/Activities.module.css
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/activities/add/Add.module.css
  src/pages/mypage/activities/add/index.tsx
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/reservations/Reservations.module.css
Labels: 🐹 Fix, 🐸 Refactor

#125 [#117] 예약 현황페이지 리팩토링 및 성능 개선
  src/components/MyPage/MyPageLayout.module.css
  src/components/MyPage/MyPageLayout.tsx
  src/components/ReservationDashboard/Calendar/Calendar.module.css
  src/components/ReservationDashboard/Calendar/CalendarHeader.tsx
  src/components/common/DropDown/Dropdown.module.css
  src/components/common/DropDown/Dropdown.tsx
Labels: 🐹 Fix, 🐸 Refactor

#115 [#105] 메인페이지 리팩토링
  public/icons/icon-close.svg
  public/icons/icon-refresh.svg
  src/components/Home/AllExperience/AllExperience.tsx
  src/components/Home/Banner/Banner.module.css
  src/components/Home/Banner/Banner.tsx
  src/components/Home/Card/Card.module.css
  src/components/Home/Card/Card.tsx
  src/components/Home/CardDetail/CardDetail.module.css
  src/components/Home/CardDetail/CardDetail.tsx
  src/components/Home/PopularExperience/PopularExperience.module.css
  src/components/Home/PopularExperience/PopularExperience.tsx
  src/components/Home/Searchbar/Searchbar.module.css
  src/components/Home/Searchbar/Searchbar.tsx
  src/components/ReservationDashboard/Calendar/Calendar.tsx
  src/components/ReservationDashboard/Modal/Modal.tsx
  src/components/ReservationDashboard/Modal/ModalContent.tsx
  src/components/ReservationDashboard/Modal/ModalDetailedCard.module.css
  src/components/ReservationDashboard/Modal/ModalDetailedCard.tsx
  src/components/common/Pagination/Pagination.module.css
  src/components/common/Pagination/Pagination.tsx
  src/hooks/Home/useBanner.ts
  src/hooks/Home/useHome.ts
  src/hooks/ReservationDashboard/useModalContent.ts
  src/hooks/ReservationDashboard/useModalDetailedCard.ts
  src/pages/Home.module.css
  src/pages/index.tsx
  src/pages/test/index.tsx
Labels: 🐷 Feat, 🐹 Fix, 🐳 Style, 🐸 Refactor

#133 [#130] 1차 QA 반영
  public/images/TodayTripLogo2.png
  public/images/img-TodayTripLogo.png
  src/components/HeadMeta/HeadMeta.tsx
  src/pages/mypage/reservations/[id]/ReservationId.module.css
  src/pages/mypage/reservations/[id]/index.tsx
Labels: 🐹 Fix

#136 [#134] 404, 500 페이지 작성 및 페이지 리다이렉트 구현
  src/pages/404/404.module.css
  src/pages/404/index.tsx
  src/pages/500/index.tsx
  src/pages/_app.tsx
  src/pages/activities/[id]/index.tsx
  src/pages/mypage/activities/[id]/edit/index.tsx
  src/pages/mypage/reservations/[id]/index.tsx
Labels: 🐷 Feat

#137 [#131] 로그인, 회원가입, 알림모달 1차 QA 반영
  src/components/Input/Checkbox.module.css
  src/components/Input/Input.module.css
  src/components/User/SocialLogin.tsx
  src/components/common/Navbar/AlarmModal.module.css
  src/components/common/Navbar/AlarmModal.tsx
  src/components/common/Navbar/Navbar.tsx
  src/constants/user.ts
  src/pages/signin/SignIn.module.css
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🐸 Refactor

#135 [#132] 1차 QA 반영
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Activities/Add/MapContainer.tsx
  src/components/common/DropDown/Dropdown.module.css
  src/components/common/DropDown/Dropdown.tsx
  src/components/common/Navbar/AlarmModal.module.css
  src/components/common/Navbar/Navbar.tsx
  src/pages/mypage/activities/Activities.module.css
Labels: 🐹 Fix

#128 [#99] 체험 상세 및 예약 내역 페이지 리팩토링 및 성능 개선
  next.config.js
  src/components/Activities/Header/Header.module.css
  src/components/Activities/Header/Header.tsx
  src/components/Activities/ReservationDateTimePicker/AvailableSchedules/AvailableSchedules.module.css
  src/components/Activities/ReservationDateTimePicker/AvailableSchedules/AvailableSchedules.tsx
  src/components/Activities/ReservationDateTimePicker/ParticipantsPicker/ParticipantsPicker.module.css
  src/components/Activities/ReservationDateTimePicker/ParticipantsPicker/ParticipantsPicker.tsx
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.module.css
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.tsx
  src/components/Activities/ReviewList/ReviewList.module.css
  src/components/Activities/ReviewList/ReviewList.tsx
  src/components/FilterDropdown/FilterDropdown.tsx
  src/components/Home/AllExperience/AllExperience.tsx
  src/components/Modal/ReservationModal/ReservationModal.tsx
  src/components/MyPage/Activities/ActivitiesCard.tsx
  src/components/MyPage/Activities/Add/ReservationTime.tsx
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.module.css
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.tsx
  src/components/ReservationDashboard/Modal/ModalContent.tsx
  src/components/common/Map/Map.tsx
  src/components/common/Navbar/AlarmModal.tsx
  src/components/common/NoResult/NoResult.module.css
  src/components/common/NoResult/NoResult.tsx
  src/constants/dropdown.ts
  src/constants/reservation.ts
  src/pages/Home.module.css
  src/pages/activities/[id]/index.tsx
  src/pages/api/geocode.ts
  src/pages/index.tsx
  src/pages/mypage/activities/Activities.module.css
  src/pages/mypage/activities/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/types/myActivities/index.ts
  src/types/myReservations/index.ts
Labels: 🐸 Refactor

#143 [#142] maps 오류 1차 시도
  src/components/common/Map/Map.tsx
Labels: 🐹 Fix

#148 Update README.md
  README.md
Labels: 🦄 Docs

#144 [#140] 로그인, 회원가입, 내 정보 페이지 2차 QA
  src/components/Input/CheckboxInput.tsx
  src/components/MyPage/Activities/Add/ReservationTime.tsx
  src/components/common/Navbar/Navbar.tsx
  src/pages/mypage/index.tsx
Labels: 🐹 Fix

#145 [#138] 2차 QA 반영
  public/images/img-TodayTripLogo.png
  src/components/common/Button/Button.module.css
  src/pages/mypage/reservations/[id]/index.tsx
Labels: 🐹 Fix, 🐸 Refactor

#150 [#139] 2차 QA 반영
  src/components/Activities/Header/Header.module.css
  src/components/Activities/Header/Header.tsx
  src/components/Activities/ReservationDateTimePicker/ReservationCalendar/ReservationCalendar.module.css
  src/components/Activities/ReservationDateTimePicker/ReservationCalendar/ReservationCalendar.tsx
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.module.css
  src/components/Activities/ReservationDateTimePicker/ReservationDateTimePicker.tsx
  src/components/FilterDropdown/FilterDropdown.module.css
  src/components/FilterDropdown/FilterDropdown.tsx
  src/components/Modal/ReservationModal/ReservationModal.module.css
  src/components/Modal/ReservationModal/ReservationModal.tsx
  src/components/MyPage/Reservations/ReservationCard/ReservationCard.module.css
  src/hooks/Activities/useAvailableScheduleFilter.ts
  src/pages/mypage/reservations/index.tsx
Labels: 🐹 Fix

#152 Fix: 사용하지 않는 redux 관련 dependencies 삭제 #151
  package-lock.json
  package.json
Labels: 🐹 Fix

#157 [#154] 예약 현황 페이지 드랍다운 아이템 변경시 모달 내용 바뀌지 않는 오류 해결
  src/components/ReservationDashboard/Modal/ModalContent.tsx
  src/components/ReservationDashboard/Modal/ModalDetailedCard.tsx
  src/hooks/ReservationDashboard/useModal.ts
  src/hooks/ReservationDashboard/useModalDetailedCard.ts
Labels: 🐹 Fix

#158 Fix: 예약 현황 모달 무한스크롤 안되는 오류 수정
  src/components/ReservationDashboard/Modal/ModalContent.tsx
  src/hooks/ReservationDashboard/useModalContent.ts
Labels: 🐹 Fix
