Repository TripTripNow/TodayTrip, pull requests merged in 2024-01, with the labels that each got.

#6 Feat: constants폴더 생성 #5
  src/constants/.gitkeep
Labels: 🐷 Feat

#8 [# 3] husky&lint-staged 추가 및 github actions
  .eslintrc.json
  .github/workflows/ci.yml
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 🐷 Feat

#7 [#2] css, react-query, axios, font 초기 설정 및 eslint 수정
  .eslintrc.json
  .prettierrc
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  prettier.config.ts
  public/fonts/.gitkeep
  public/fonts/Pretandard/Pretandard.css
  public/fonts/Pretandard/Pretendard-Bold.woff
  public/fonts/Pretandard/Pretendard-Bold.woff2
  public/fonts/Pretandard/Pretendard-ExtraLight.woff
  public/fonts/Pretandard/Pretendard-ExtraLight.woff2
  public/fonts/Pretandard/Pretendard-Medium.woff
  public/fonts/Pretandard/Pretendard-Medium.woff2
  public/fonts/Pretandard/Pretendard-Regular.woff
  public/fonts/Pretandard/Pretendard-Regular.woff2
  public/fonts/Pretandard/Pretendard-SemiBold.woff
  public/fonts/Pretandard/Pretendard-SemiBold.woff2
  public/icons/.gitkeep
  public/icons/icon-logo.svg
  src/api/axiosInstance.ts
  src/apis/.gitkeep
  src/pages/_app.tsx
  src/styles/globals.css
  src/styles/reset.css
  src/types/custom.d.ts
  tailwind.config.ts
  tsconfig.json
Labels: 🐷 Feat, 🐳 Style

#17 [#16] 글로벌 CSS 설정
  src/pages/_app.tsx
  src/styles/breakpoints.css
  src/styles/variables.css
Labels: 🐷 Feat

#21 [#20] ReactQueryDevtools 폰트 오류 및 Pretendard 폰트 적용 오류 해결
  src/pages/_app.tsx
  src/styles/globals.css
  src/styles/reset.css
Labels: 🐹 Fix

#22 [#11] Input 컴포넌트
  .vscode/settings.json
  src/components/.gitkeep
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
Labels: 🐷 Feat

#27 [#23] signin, signup
  public/images/.gitkeep
  public/images/img-google.png
  public/images/img-kakao.png
  public/images/img-logo.png
  public/images/img-naver.png
  src/components/Input/Checkbox.module.css
  src/components/Input/CheckboxInput.tsx
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
  src/components/User/SocialLogin.module.css
  src/components/User/SocialLogin.tsx
  src/components/User/UserLayout.module.css
  src/components/User/UserLayout.tsx
  src/constants/.gitkeep
  src/constants/user.ts
  src/pages/_app.tsx
  src/pages/signin/SignIn.module.css
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🐷 Feat

#38 [#28] mypage 레이아웃 및 내정보 페이지
  public/icons/icon-activities.svg
  public/icons/icon-dashboard.svg
  public/icons/icon-edit.svg
  public/icons/icon-mypage.svg
  public/icons/icon-reservation.svg
  public/images/img-logo.png
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
  src/components/MyPage/MyPageLayout.module.css
  src/components/MyPage/MyPageLayout.tsx
  src/components/MyPage/ProfileInput.tsx
  src/components/MyPage/ProfileMenuBox.module.css
  src/components/MyPage/ProfileMenuBox.tsx
  src/components/MyPage/profileInput.module.css
  src/pages/mypage/MyPage.module.css
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/utils/passwordCheck.ts
Labels: 🐷 Feat

#36 [#35] 푸터 컴포넌트 구현
  src/components/Footer/Footer.module.css
  src/components/Footer/Footer.tsx
  src/pages/_app.tsx
  src/pages/test/index.tsx
Labels: 🐷 Feat

#33 [#13] Navbar 구현
  public/icons/icon-alarm.svg
  public/icons/icon-blueEllipse.svg
  public/icons/icon-close.svg
  public/icons/icon-lightClose.svg
  public/icons/icon-logo.svg
  public/icons/icon-profile.svg
  public/icons/icon-redEllipse.svg
  src/components/Modal/ModalLayout/ModalLayout.module.css
  src/components/Modal/ModalLayout/ModalLayout.tsx
  src/components/Navbar/AlarmModal.module.css
  src/components/Navbar/AlarmModal.tsx
  src/components/Navbar/ProfileDropDown.module.css
  src/components/Navbar/ProfileDropDown.tsx
  src/components/common/Navbar.module.css
  src/components/common/Navbar.tsx
  src/pages/_app.tsx
Labels: 🐷 Feat

#50 [#49] 내 정보 페이지 버튼 컴포넌트 교체
  src/pages/mypage/index.tsx
Labels: 🐷 Feat

#34 [#32] 필터 드롭다운 컴포넌트 구현
  public/icons/icon-arrowDown-solid.svg
  src/components/FilterDropdown/FilterDropdown.module.css
  src/components/FilterDropdown/FilterDropdown.tsx
  src/constants/dropdown.ts
  src/pages/_app.tsx
Labels: 🐷 Feat

#39 [#26] 예약 내역 페이지 구현
  .github/ISSUE_TEMPLATE/feature.yml
  package-lock.json
  package.json
  public/icons/icon-emptyStar.svg
  public/icons/icon-lightYellowStar.svg
  public/icons/icon-modalClose.svg
  public/icons/icon-yellowStar.svg
  src/components/FilterDropdown/FilterDropdown.module.css
  src/components/FilterDropdown/FilterDropdown.tsx
  src/components/Modal/AlertModal/AlertModal.module.css
  src/components/Modal/AlertModal/AlertModal.tsx
  src/components/Modal/ReviewModal/ReviewModal.module.css
  src/components/Modal/ReviewModal/ReviewModal.tsx
  src/components/Modal/ReviewModal/Star/Star.tsx
  src/components/MyPage/ProfileInput.tsx
  src/components/MyPage/ProfileMenuBox.tsx
  src/components/MyPage/profileInput.module.css
  src/components/Navbar/AlarmModal.tsx
  src/components/Reservations/Card/Card.module.css
  src/components/Reservations/Card/Card.tsx
  src/components/Reservations/mock.ts
  src/components/User/UserLayout.tsx
  src/components/common/Button/Button.module.css
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/DropDown/Dropdown.tsx
  src/components/common/Navbar.tsx
  src/constants/dropdown.ts
  src/constants/reservation.ts
  src/hooks/.gitkeep
  src/hooks/useInfiniteScroll.ts
  src/pages/mypage/reservations/Reservations.module.css
  src/pages/mypage/reservations/index.tsx
  src/pages/test/index.tsx
  src/types/.gitkeep
  src/types/custom.d.ts
  src/types/dropdown.ts
  src/types/reservations.ts
  src/utils/.gitkeep
  src/utils/formatDateString.ts
Labels: 🐷 Feat

#42 [#10] 메인화면 페이지 작성
  .eslintrc.json
  package-lock.json
  package.json
  public/icons/icon-left-arrow.svg
  public/icons/icon-no-result.svg
  public/icons/icon-pagination-left-arrow.svg
  public/icons/icon-pagination-right-arrow.svg
  public/icons/icon-right-arrow.svg
  public/icons/icon-search.svg
  public/images/img-carousel1.png
  public/images/img-carousel2.png
  public/images/img-carousel3.png
  src/components/FilterDropdown/FilterDropdown.tsx
  src/components/Home/AllExperience/AllExperience.module.css
  src/components/Home/AllExperience/AllExperience.tsx
  src/components/Home/Banner/Banner.module.css
  src/components/Home/Banner/Banner.tsx
  src/components/Home/Card/Card.module.css
  src/components/Home/Card/Card.tsx
  src/components/Home/CardDetail/CardDetail.module.css
  src/components/Home/CardDetail/CardDetail.tsx
  src/components/Home/NoResult/NoResult.module.css
  src/components/Home/NoResult/NoResult.tsx
  src/components/Home/PopularExperience/PopularExperience.module.css
  src/components/Home/PopularExperience/PopularExperience.tsx
  src/components/Home/Searchbar/Searchbar.module.css
  src/components/Home/Searchbar/Searchbar.tsx
  src/components/common/Button/Button.module.css
  src/components/common/Button/Button.tsx
  src/components/common/Pagination/Pagination.module.css
  src/components/common/Pagination/Pagination.tsx
  src/constants/mock.ts
  src/hooks/common/useDeviceType.ts
  src/pages/Home.module.css
  src/pages/index.tsx
  src/pages/mypage/reservations/index.tsx
  src/types/api.ts
  src/types/react-splide.d.ts
  src/utils/intToFloat.ts
  src/utils/localStorage.ts
  src/utils/priceFormat.ts
Labels: 🐷 Feat, 🐹 Fix, 🐸 Refactor

#54 [#46] 카테고리 드랍다운 컴포넌트 수정
  src/components/common/DropDown/Dropdown.module.css
  src/components/common/DropDown/Dropdown.tsx
  src/pages/mypage/activities/reservation-dashboard/ReservationDashboard.module.css
  src/pages/mypage/activities/reservation-dashboard/index.tsx
Labels: 🐹 Fix, 🐳 Style
